# Generated by Django 4.2 on 2023-04-29 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='print',
            new_name='price',
        ),
    ]
